Auto calculate the audio track using mediainfo, be quieter also

diff --git a/bin/aac2ac3 b/bin/aac2ac3
--- a/bin/aac2ac3
+++ b/bin/aac2ac3
@@ -2,9 +2,6 @@ INPUT=$1
 OUTPUT=$2
 WORKDIR=$3
 
-# make things a bit more pretty
-echo
-
 # make sure all programs we need are installed
 if ! which mkvmerge mkvextract &> /dev/null
 then
@@ -21,6 +18,12 @@ fi
 if ! which aften &> /dev/null
 then
    echo "Aften is missing.  Please install the aften package."
+   echo
+   exit 1
+fi
+if ! which mediainfo &> /dev/null
+then
+   echo "MediaInfo is missing. Please install the mediainfo package."
    echo
    exit 1
 fi
@@ -88,43 +91,23 @@ fi
 # check if the input file is an MP4 file
 if [[ "$INPUT" == *.mp4 ]] || [[ "$INPUT" == *.MP4 ]]
 then
-   mkvmerge --no-chapters -o "$WORKDIR/AAC2AC3Temp.mkv" "$INPUT"
+   mkvmerge -q --no-chapters -o "$WORKDIR/AAC2AC3Temp.mkv" "$INPUT"
    INPUT="$WORKDIR/AAC2AC3Temp.mkv"
-   echo
-   echo "**********"
-   echo
 fi
 
-# print out details about the file in question
-mkvmerge -i "$INPUT"
+# figure out the 6 channel audio track
+TRACK=`mediainfo "$INPUT" | grep -B9 '6 channels' | grep -B1 AAC | grep ID | sed 's/[^0-9]//g'`
 
-# ask which track we are converting
-echo
-echo -n "Please specify track to be converted (look for the (A_AAC) label): "
-read TRACK
-echo
-
-# check if the track was properly specified
-if [ "`expr $TRACK - $TRACK 2> /dev/null`" != "0" ]
+if [ "x$TRACK" == "x" ]
 then
-   echo "Specified track has to be a numeric value."
    echo
-   exit 1
-fi
-if [ $TRACK -lt 1 ]
-then
-   echo "Specified track can not be less than one."
+   echo "Could not determine the correct audio track."
    echo
    exit 1
 fi
 
 # extract the specified track
-mkvextract tracks "$INPUT" $TRACK:"$WORKDIR/AAC2AC3Temp.aac"
-
-# make things pretty
-echo
-echo "**********"
-echo
+mkvextract -q tracks "$INPUT" $TRACK:"$WORKDIR/AAC2AC3Temp.aac"
 
 RATE=48000
 CHANNELS=6
@@ -132,20 +115,11 @@ CHANNELS=6
 # faad outputs a raw 24 bit PCM stream (anything higher than 24 bits seems to
 # introduce anomalies) which is then piped to aften and converted to a 640 kbit/s
 # AC3 stream (640 kbit/s is max allowed and yields highest possible quality)
-faad -b 2 -f 2 -q -w "$WORKDIR/AAC2AC3Temp.aac" | aften -v 1 -b 640 \
+faad -b 2 -f 2 -q -w "$WORKDIR/AAC2AC3Temp.aac" | aften -v 0 -b 640 \
 -raw_fmt s24_le -raw_sr $RATE -raw_ch $CHANNELS -chmap 0 - "$WORKDIR/AAC2AC3Temp.ac3"
 
-# make things pretty
-echo "**********"
-echo
-
-APPENDREPLACE="r"
-
 # merge everything back together (except audio tracks from original file)
-mkvmerge -o "$OUTPUT" -A "$INPUT" "$WORKDIR/AAC2AC3Temp.ac3"
-
-# make things pretty
-echo
+mkvmerge -q -o "$OUTPUT" -A "$INPUT" "$WORKDIR/AAC2AC3Temp.ac3"
 
 # clean up temp files
 rm -f "$WORKDIR/AAC2AC3Temp.mkv"
